### ISSUE TITLE
404-Seite erweitern/anpassen

### ISSUE THREAD

**Issue by janoevermann** [plusmeta/blog#6]
Die Datei 404.md wird angezeigt, wenn der Benutzer z.B. auf einen Link navigiert, den es nicht mehr gibt ("Seite nicht gefunden"). Diese sollte für plusmeta angepasst werden.

**Comment by fabiennelange** [comment]
Ideen: 

- abgestürzte Rakete

- Rakete, die sich verflogen hat

- Rakete statt der 0 in 404
